# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField(default=0)),
                ('recurrence', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('score', models.FloatField(default=0)),
                ('recurrence', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('score', models.FloatField(default=0)),
                ('recurrence', models.PositiveIntegerField(default=0)),
                ('added_day', models.DateField(auto_now_add=True)),
                ('updated_day', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.Word'),
        ),
        migrations.AddField(
            model_name='date',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.State'),
        ),
    ]
